language: python
os: linux
dist: bionic
python:
  - "3.11"
  
install:
  - pip install -r mysite/requirements.txt

before_script:
  - python mysite/manage.py makemigrations 
  - python mysite/manage.py migrate
  
script:
  - black --check .
  - flake8 .
  - coverage run mysite/manage.py test

after_script:
  - coveralls
