language: python
os: linux
dist: bionic
python:
  - "3.11"
  
install:
  - pip install -r mysite/requirements.txt
  - pip install coveralls
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

before_script:
  - python mysite/manage.py makemigrations 
  - python mysite/manage.py migrate
  
  
script:
  - black --check .
  - flake8 .
  - coverage run mysite/manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml


after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "mysite"
  env: "pollsite"
  bucket_name: "elasticbeanstalk-us-east-1-907398054630"
  bucket_path: "mysite"  
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
